name: Publish to madikizavuyo.github.io

on:
  push:
    branches:
      - main # Replace with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Commit and push changes
        run:
          git config --global user.name "Vuyo Madikiza"
          git config --global user.email "madikizavuyo@gmail.com"
          git remote set-url origin https://github.com/madikizavuyo/madikizavuyo.github.io.git
          git commit -m 'First Commit to cloned repo'          
          git branch -M main
          git remote add origin https://github.com/madikizavuyo/madikizavuyo.github.io.git
          git push -u origin main
