name: Publish to madikizavuyo.github.io

on:
  push:
    branches:
      - main # Replace with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Commit and push changes
        run:
          git config user.name "Your Name"
          git config user.email "your@email.com"
          cd madikizavuyo.github.io/
          git checkout main
          cp -R ../dist/* ./
          git add .
          git commit -m "Update API documentation"
          git push origin main
