name: Publish to madikizavuyo.github.io

on:
  push:
    branches:
      - main # Replace with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Commit and push changes
        run:
          cd madikizavuyo.github.io/
          git config user.name "Vuyo Madikiza"
          git config user.email "madikizavuyo@gmail.com"
          git add .
          git commit -m "Update site"
          git push origin main
