# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main  


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build --if-present
      
      - name: Install dependencies
        run: yarn install

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with: 
          ssh-key: ${{ secrets.deploy }}
          folder: .
          repository-name: madikizavuyo/madikizavuyo.github.io
          git-config-name: Vuyo Madikiza
          git-config-email: madikizavuyo@gmail.com
          branch: test
          commit-message: another commit 2
          clean: true
